<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project3.Domain\Project3.Domain.csproj" />
    <ProjectReference Include="..\Project3.Infracture\Project3.Infrastructure.csproj" />
  </ItemGroup>

</Project>
